name: Build and Deploy Frontend

on:
  push:
    branches:
      - master  # 触发主分支推送时执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 提取仓库代码
        uses: actions/checkout@v4

      - name: 安装node.js文件
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # 可根据项目需要选择Node.js版本

      - name: 切换到项目目录
        run: cd /home/runner/work/2024/2024/qianduan
        with:
          run: npm install  # 如果是使用yarn，改为yarn install
          run: npm run qianduan


      - name: 打包存档文件
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist  # 构建生成的静态文件目录，根据项目配置修改

      - name: 部署前端应用到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages  # 发布到的分支，通常是gh-pages
          FOLDER: dist  # 构建生成的静态文件目录


