name: Build and Deploy Frontend

on:
  push:
    branches:
      - master  # 触发主分支推送时执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 提取仓库代码
        uses: actions/checkout@v4

      - name: Clean up and configure Git
        run: |
          git remote rm origin
          git remote add origin https://github.com/wamg2023/2024.git
          git config --global user.name "wamg2023"
          git config --global user.email "2366835906@qq.com"

      - name: 设置Node.js环境并安装依赖
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # 根据项目需要选择Node.js版本

      - name: 切换到项目目录并安装依赖
        run: |
          cd /home/runner/work/2024/2024/qianduan
          npm install

      - name: 运行前端构建命令
        run: |
          cd /home/runner/work/2024/2024/qianduan
          npm run qianduan

      - name: 打包存档文件
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: /home/runner/work/2024/2024/qianduan  # 构建生成的静态文件目录，根据项目配置修改

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages  # 发布到的分支，通常是 gh-pages
          FOLDER: /home/runner/work/2024/2024/qianduan  # 构建生成的静态文件目录，与上面保持一致
